on:
  push:
    branches:
      - dev
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint_and_prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check Prettier
        run: npm run prettier:check

      - name: Check Lint
        run: npm run lint

      - name: Run hardhat compile
        run: npm run compile

      - name: Type Check
        run: npm run typecheck

      - name: Test
        run: npm run test
